"""Add bio field to users table

Revision ID: a031086b3f77
Revises: b3c4d5e6f7g8
Create Date: 2025-07-16 19:21:31.674689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a031086b3f77'
down_revision: Union[str, None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_reading_progress')
    with op.batch_alter_table('tbl_reading_history', schema=None) as batch_op:
        batch_op.alter_column('time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('total_length',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_column('reading_time_seconds')
        batch_op.drop_column('last_position')

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('tbl_reading_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_position', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reading_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('total_length',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
        batch_op.alter_column('time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)

    op.create_table('tbl_user_reading_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('read_time_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('progress_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name='tbl_user_reading_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tbl_user_reading_progress_pkey')
    )
    # ### end Alembic commands ###
