"""Add sharing events table

Revision ID: c5d6e7f8g9h0
Revises: a031086b3f77
Create Date: 2025-07-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d6e7f8g9h0'
down_revision = 'a031086b3f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_sharing_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=False),
    sa.Column('share_method', sa.String(length=20), nullable=False),
    sa.Column('content_url', sa.String(length=1000), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_sharing_events')
    # ### end Alembic commands ###